version: "3.7"

services:

  php:
    build:
        context: .
        dockerfile: .docker/Dockerfile
    image: php
    ports:
        [8080:80]
    volumes:
        [.:/app]
    links:
        [db]
    environment:
        DB_HOST: mysql
        DB_DATABASE: laravel
        DB_USERNAME: app
        DB_PASSWORD: password

  db:
    image: mysql:5.7
    ports:
      [13306:3306]
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
